# Generated by Django 6.0.4 on 2026-05-04 02:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        help_text="PDF resume file (max 5MB)",
                        upload_to="resumes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, help_text="Extracted text from PDF", null=True
                    ),
                ),
                (
                    "ats_score",
                    models.IntegerField(
                        blank=True, help_text="ATS score (0-100)", null=True
                    ),
                ),
                (
                    "strengths",
                    models.JSONField(
                        blank=True, default=list, help_text="List of resume strengths"
                    ),
                ),
                (
                    "weaknesses",
                    models.JSONField(
                        blank=True, default=list, help_text="List of resume weaknesses"
                    ),
                ),
                (
                    "suggestions",
                    models.JSONField(
                        blank=True, default=list, help_text="Improvement suggestions"
                    ),
                ),
                (
                    "analysis_details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full analysis details"
                    ),
                ),
                (
                    "keywords_found",
                    models.JSONField(
                        blank=True, default=list, help_text="Keywords found in resume"
                    ),
                ),
                (
                    "job_match_score",
                    models.IntegerField(
                        blank=True, help_text="Job match percentage", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if analysis failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="resumes_res_user_id_6019d7_idx",
                    ),
                    models.Index(
                        fields=["status"], name="resumes_res_status_dd2fd3_idx"
                    ),
                ],
            },
        ),
    ]
